spring.application.name=spring-kafka-stream
server.port=8083

spring.cloud.stream.bindings.pageEventConsumer-in-0.destination=R2
spring.cloud.stream.bindings.pageEventSupplier-out-0.destination=R3
spring.cloud.stream.bindings.pageEventSupplier-out-0.producer.poller.fixed-delay=200

spring.cloud.stream.bindings.KStreamFunction-in-0.destination=R3
spring.cloud.stream.bindings.KStreamFunction-out-0.destination=R4

spring.cloud.function.definition=pageEventConsumer;pageEventSupplier;KStreamFunction
